project:
  type: website
  output-dir: docs

website:
  title: "Immanuel J Feld"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    css: bootstrap.min.css
    toc: true

editor: visual

